module.exports = {
  content: ["./src/**/*.{html,ts}", "./projects/**/*.{html,ts}"],
  darkMode: "media",
  theme: {
    fontFamily: {
      display: ["Ubuntu"],
      body: ["Ubuntu"],
    },
    container: {
      center: true,
      padding: "1.5rem",
    },
    extend: {
      colors: {
        cultured: "#F5F5F5",
        white: "#FFFFFF",
        "dropdown-bg": "#F8F8F9;",
        // 'light-black': '#232627',
        // 'black-bg': '#2E2F30',
        // 'light-orange': '#EF7B5D',
        // 'white-border': '#E4E7EC',
        // 'highlight-black': '#333339',
        // 'custom-red': '#DC3545',
        // 'warning-bg': '#F9EAEB',
        // grey: '#575E7A',
        // 'blue-buy': '#6081FA',
        // 'red-sell': '#EA4D5C',
        // 'green-buy': '#53B988',
        // 'white-balance': '#D8D8D8',
        // 'gray-txt': '#AAAAAA',
        // 'custom-black': '#2B2B2D',
        // 'grey-txt': '#8890A3',
        // 'grey-border': '#525865',
      },
      // backgroundImage: {
      //   'logo-with-text': "url('/assets/logo-with-text.svg')",
      //   'arrow-down': "url('/assets/caret-down.svg')",
      // },
      fontSize: {
        xs: ".75rem",
        sm: ".875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "3.2xl": "2rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
        "6xl": "4rem",
        "7xl": "5rem",
        "8xl": "6rem",
      },
      spacing: {
        0: "0px",
        0.5: "0.125rem",
        1: "0.25rem",
        1.5: "0.375rem",
        2: "0.5rem",
        2.5: "0.625rem",
        3: "0.75rem",
        3.5: "0.825rem",
        4: "1rem",
        12: "3rem",
      },
      minWidth: {
        10: "10rem",
        8: "8rem",
        12.5: "12.5rem",
        "1/2": "50%",
      },
    },
  },
  plugins: [],
};
